### ISSUE TITLE
Googletest bug on IMAS

### ISSUE THREAD

**Issue by olaszsoma** [gergopokol/Runin#1]
The make file of Runin creates a test_imas.bin file after running the test.sh script. This script, after finishing the make looks for a .bin file named test.bin to run for both IMAS and ITM, hence the testing does not work for IMAS.

**Comment by olaszsoma** [comment]
I will modify the the make file to create test.bin file for both IMAS and ITM environment.

**Comment by olaszsoma** [comment]
The modification have been tested and solved.

**Comment by olaszsoma** [comment]
#2 Hofix merged to master.

**Comment by gergopokol** [comment]
Correcting message for missing GTEST.

**Comment by olaszsoma** [comment]
Modifications have been uploaded to the hotfix-googletest branch, ready to merge.
